version : '3.8'

services:
  rest:
    build: rest/
    restart: unless-stopped
#    environment:
#      - DATABASE_URL=jdbc:postgresql://db:5432/paperlessdb
#      - DATABASE_USER=postgres
#      - DATABASE_PWD=postgres
    ports:
      - 8081:8081

