version: '3.8'

services:
  rest:
    build: rest
    container_name: paperless-rest
    restart: unless-stopped
    ports:
      - "8081:8081"
  ui:
    build: ui
    container_name: paperless-ui
    restart: unless-stopped
    ports:
      - "80:80"


