version: '3.8'

services:
  rest:
    build: rest
    container_name: paperless-rest
    restart: unless-stopped
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - paperless_network

  ui:
    build: ui
    container_name: paperless-ui
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - rest
    networks:
      - paperless_network

networks:
  paperless_network:
    driver: bridge
