version: '3.8'

services:
  rest:
    build: rest
    container_name: paperless-rest
    restart: unless-stopped
    ports:
      - "8081:8081"
  ui:
    build: ui
    container_name: paperless-ui
    restart: unless-stopped
    ports:
      - "80:80"
  paperless-db:
    build: paperless-db/.
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
