version: '3.8'

services:
  db:
    build: db/.
    restart: always
    container_name: paperless-db
    hostname: db
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=paperlessdb
    networks:
      - paperless
  rest:
    build: rest
    container_name: paperless-rest
    hostname: rest
    restart: unless-stopped
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      - db
    networks:
      - paperless
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/paperlessdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
  ui:
    build: ui
    container_name: paperless-ui
    hostname: ui
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - paperless
  queue:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - paperless


networks:
  paperless:
    driver: bridge