version: '3.8'

services:
  db:
    build: db/.
    container_name: paperless-db
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=paperlessdb
    networks:
      - paperless
  rest:
    build: rest
    container_name: paperless-rest
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - paperless
  ui:
    build: ui
    container_name: paperless-ui
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - paperless

networks:
  paperless:
    driver: bridge